import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#7C3AED',
  secondary: '#06D6A0',
  background: '#121212',
  backgroundDark: '#0A0A0A',
  white: '#FFFFFF',
  black: '#000000',
  text: '#FFFFFF',
  textLight: '#B0B0B0',
  textLighter: '#808080',
  border: 'rgba(255, 255, 255, 0.08)',
  disabled: '#4A4A4A',
  success: '#10B981',
  cardBg: 'rgba(45, 45, 50, 0.65)',
  shadow: 'rgba(124, 58, 237, 0.25)',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    padding: 30,
    paddingTop: 50,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    letterSpacing: -1,
  },
  headerSubtitle: {
    fontSize: 15,
    color: colors.white,
    opacity: 0.9,
    textAlign: 'center',
    marginTop: 6,
    letterSpacing: -0.2,
  },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 10,
    justifyContent: 'space-between',
  },
  menuItem: {
    width: '30%',
    aspectRatio: 1,
    backgroundColor: colors.cardBg,
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  menuIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  menuIconText: {
    fontSize: 24,
    color: colors.white,
  },
  menuText: {
    fontSize: 13,
    color: colors.text,
    textAlign: 'center',
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  footer: {
    padding: 20,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: colors.textLighter,
  },
  screenHeader: {
    backgroundColor: colors.primary,
    padding: 20,
    paddingTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    fontSize: 18,
    color: colors.white,
    fontWeight: '600',
    marginRight: 15,
  },
  screenTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.white,
  },
  formCard: {
    backgroundColor: colors.cardBg,
    margin: 20,
    padding: 28,
    borderRadius: 24,
    elevation: 6,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  inputLabel: {
    fontSize: 15,
    color: colors.textLight,
    marginBottom: 10,
    marginTop: 18,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  inputField: {
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    color: colors.text,
    backgroundColor: 'rgba(55, 55, 60, 0.6)',
    letterSpacing: -0.2,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    padding: 18,
    borderRadius: 24,
    alignItems: 'center',
    marginTop: 28,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 19,
    fontWeight: 'bold',
    letterSpacing: -0.4,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    padding: 18,
    borderRadius: 24,
    alignItems: 'center',
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 19,
    fontWeight: 'bold',
    letterSpacing: -0.4,
  },
  sectionTitle: {
    fontSize: 18,
    color: colors.text,
    marginTop: 28,
    marginBottom: 8,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: -0.4,
  },
  disabledButton: {
    backgroundColor: colors.disabled,
    borderColor: colors.disabled,
  },
  helperText: {
    fontSize: 13,
    color: colors.textLighter,
    textAlign: 'center',
    marginTop: 15,
  },
  qrScanButton: {
    backgroundColor: colors.primary,
    marginHorizontal: 20,
    marginVertical: 16,
    padding: 22,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
  },
  qrScanIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  qrScanText: {
    fontSize: 19,
    fontWeight: 'bold',
    color: colors.white,
    letterSpacing: -0.4,
  },
});
