import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#2c2c2c',
  secondary: '#404040',
  background: '#fafafa',
  backgroundDark: '#f5f5f5',
  white: '#ffffff',
  black: '#1a1a1a',
  text: '#2c2c2c',
  textLight: '#6b6b6b',
  textLighter: '#9e9e9e',
  border: '#e8e8e8',
  disabled: '#d4d4d4',
  success: '#2c2c2c',
  cardBg: '#ffffff',
  shadow: '#000000',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    padding: 30,
    paddingTop: 50,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.white,
    opacity: 0.9,
    textAlign: 'center',
    marginTop: 5,
  },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 10,
    justifyContent: 'space-between',
  },
  menuItem: {
    width: '30%',
    aspectRatio: 1,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  menuIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  menuIconText: {
    fontSize: 24,
    color: colors.white,
  },
  menuText: {
    fontSize: 12,
    color: colors.text,
    textAlign: 'center',
    fontWeight: '500',
  },
  footer: {
    padding: 20,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: colors.textLighter,
  },
  screenHeader: {
    backgroundColor: colors.primary,
    padding: 20,
    paddingTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    fontSize: 18,
    color: colors.white,
    fontWeight: '600',
    marginRight: 15,
  },
  screenTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.white,
  },
  formCard: {
    backgroundColor: colors.white,
    margin: 20,
    padding: 25,
    borderRadius: 20,
    elevation: 4,
  },
  inputLabel: {
    fontSize: 14,
    color: colors.textLight,
    marginBottom: 8,
    marginTop: 15,
    fontWeight: '600',
  },
  inputField: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: colors.text,
    backgroundColor: '#f9f9f9',
  },
  primaryButton: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 25,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  secondaryButton: {
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 15,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  sectionTitle: {
    fontSize: 16,
    color: colors.text,
    marginTop: 25,
    marginBottom: 5,
    fontWeight: '700',
    textAlign: 'center',
  },
  disabledButton: {
    backgroundColor: colors.disabled,
    borderColor: colors.disabled,
  },
  helperText: {
    fontSize: 13,
    color: colors.textLighter,
    textAlign: 'center',
    marginTop: 15,
  },
  qrScanButton: {
    backgroundColor: colors.primary,
    marginHorizontal: 20,
    marginVertical: 15,
    padding: 20,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  qrScanIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  qrScanText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
  },
});
